### ISSUE TITLE
Plugin zip

### ISSUE THREAD

**Issue by borismod** [dpiessens/tfs-worktiem-plugin#3]
How can I create a plugin Zip? Is it possible to publish it on the releases page?

**Comment by dpiessens** [comment]
The last built and tested plugin for this is on the releases page:

https://github.com/dpiessens/tfs-worktiem-plugin/releases 

If you want to build it yourself you'll need to have maven and run `mvn package` to create the .zip. It should end up in a folder off the root called targets.

Note that several people logged issues about newer versions and I haven't tested it on those versions so it may not work on new versions of TC.
